/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Omar
 */
public class InputGradeOfCard extends javax.swing.JFrame {

    /**
     * Creates new form InputGradeOfCard
     */
    public InputGradeOfCard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        orderDetailsPanel = new javax.swing.JPanel();
        boxDimensionPanel = new javax.swing.JPanel();
        lblLength = new javax.swing.JLabel();
        lblWidth = new javax.swing.JLabel();
        lblHeight = new javax.swing.JLabel();
        lblDimensions = new javax.swing.JLabel();
        lblOrderLength = new javax.swing.JLabel();
        lblOrderWidth = new javax.swing.JLabel();
        lblOrderHeight = new javax.swing.JLabel();
        lblColour = new javax.swing.JLabel();
        lblOrderColours = new javax.swing.JLabel();
        lblReinforcement = new javax.swing.JLabel();
        lblOrderReinforcement = new javax.swing.JLabel();
        lblSealableTop = new javax.swing.JLabel();
        lblOrderSealableTop = new javax.swing.JLabel();
        lblQuantity = new javax.swing.JLabel();
        lblOrderQuantity = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblChooseGrade = new javax.swing.JLabel();
        chooseGrade = new javax.swing.JComboBox();
        lblOrder = new javax.swing.JLabel();
        yesOrder = new javax.swing.JRadioButton();
        noOrder = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        btnCancel = new javax.swing.JButton();
        btnOK = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Grade of Card");
        setPreferredSize(new java.awt.Dimension(336, 499));
        setResizable(false);

        orderDetailsPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblLength.setText("Length:");

        lblWidth.setText("Width:");

        lblHeight.setText("Height:");

        lblDimensions.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblDimensions.setText("Dimensions of box (m):");

        lblOrderLength.setText("orderLength");

        lblOrderWidth.setText("orderWidth");

        lblOrderHeight.setText("orderHeight");

        lblColour.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblColour.setText("Colours needed:");

        lblOrderColours.setText("None");

        lblReinforcement.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblReinforcement.setText("Reinforcement:");

        lblOrderReinforcement.setText("None");

        lblSealableTop.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblSealableTop.setText("Sealable top:");

        lblOrderSealableTop.setText("No");

        lblQuantity.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblQuantity.setText("Qantity required:");

        lblOrderQuantity.setText("100");

        javax.swing.GroupLayout boxDimensionPanelLayout = new javax.swing.GroupLayout(boxDimensionPanel);
        boxDimensionPanel.setLayout(boxDimensionPanelLayout);
        boxDimensionPanelLayout.setHorizontalGroup(
            boxDimensionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(boxDimensionPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(boxDimensionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDimensions)
                    .addComponent(lblColour)
                    .addComponent(lblReinforcement)
                    .addComponent(lblSealableTop)
                    .addComponent(lblQuantity))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(boxDimensionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblOrderQuantity)
                    .addComponent(lblOrderSealableTop)
                    .addComponent(lblOrderReinforcement)
                    .addGroup(boxDimensionPanelLayout.createSequentialGroup()
                        .addGroup(boxDimensionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblHeight)
                            .addComponent(lblWidth)
                            .addComponent(lblLength))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(boxDimensionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblOrderLength)
                            .addComponent(lblOrderWidth)
                            .addComponent(lblOrderHeight)))
                    .addComponent(lblOrderColours))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        boxDimensionPanelLayout.setVerticalGroup(
            boxDimensionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(boxDimensionPanelLayout.createSequentialGroup()
                .addGroup(boxDimensionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDimensions)
                    .addGroup(boxDimensionPanelLayout.createSequentialGroup()
                        .addGroup(boxDimensionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblLength)
                            .addComponent(lblOrderLength))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(boxDimensionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblWidth)
                            .addComponent(lblOrderWidth))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(boxDimensionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblHeight)
                            .addComponent(lblOrderHeight))))
                .addGap(15, 15, 15)
                .addGroup(boxDimensionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblColour)
                    .addComponent(lblOrderColours))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(boxDimensionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblReinforcement)
                    .addComponent(lblOrderReinforcement))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(boxDimensionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSealableTop)
                    .addComponent(lblOrderSealableTop))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addGroup(boxDimensionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblQuantity)
                    .addComponent(lblOrderQuantity))
                .addContainerGap())
        );

        javax.swing.GroupLayout orderDetailsPanelLayout = new javax.swing.GroupLayout(orderDetailsPanel);
        orderDetailsPanel.setLayout(orderDetailsPanelLayout);
        orderDetailsPanelLayout.setHorizontalGroup(
            orderDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(orderDetailsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(boxDimensionPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        orderDetailsPanelLayout.setVerticalGroup(
            orderDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(orderDetailsPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(boxDimensionPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jLabel4.setText("Order details:");

        lblChooseGrade.setText("Choose your required grade of card:");

        chooseGrade.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4" }));
        chooseGrade.setToolTipText("");
        chooseGrade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chooseGradeActionPerformed(evt);
            }
        });

        lblOrder.setText("Would you like to place another order?");

        yesOrder.setText("Yes");

        noOrder.setSelected(true);
        noOrder.setText("No");

        jLabel3.setText("Page 2 of 2");

        btnCancel.setText("Cancel");

        btnOK.setText("OK");
        btnOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOKActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(orderDetailsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblChooseGrade)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(chooseGrade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblOrder)
                        .addGap(18, 18, 18)
                        .addComponent(yesOrder)
                        .addGap(10, 10, 10)
                        .addComponent(noOrder)))
                .addContainerGap(31, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnOK)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCancel)
                        .addGap(96, 96, 96))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addGap(35, 35, 35)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(orderDetailsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblChooseGrade)
                    .addComponent(chooseGrade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblOrder)
                    .addComponent(yesOrder)
                    .addComponent(noOrder))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 101, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnOK)
                    .addComponent(btnCancel))
                .addGap(34, 34, 34))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void chooseGradeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chooseGradeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chooseGradeActionPerformed

    private void btnOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOKActionPerformed
        new Quote().setVisible(true);

    }//GEN-LAST:event_btnOKActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InputGradeOfCard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InputGradeOfCard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InputGradeOfCard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InputGradeOfCard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InputGradeOfCard().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel boxDimensionPanel;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnOK;
    private javax.swing.JComboBox chooseGrade;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lblChooseGrade;
    private javax.swing.JLabel lblColour;
    private javax.swing.JLabel lblDimensions;
    private javax.swing.JLabel lblHeight;
    private javax.swing.JLabel lblLength;
    private javax.swing.JLabel lblOrder;
    private javax.swing.JLabel lblOrderColours;
    private javax.swing.JLabel lblOrderHeight;
    private javax.swing.JLabel lblOrderLength;
    private javax.swing.JLabel lblOrderQuantity;
    private javax.swing.JLabel lblOrderReinforcement;
    private javax.swing.JLabel lblOrderSealableTop;
    private javax.swing.JLabel lblOrderWidth;
    private javax.swing.JLabel lblQuantity;
    private javax.swing.JLabel lblReinforcement;
    private javax.swing.JLabel lblSealableTop;
    private javax.swing.JLabel lblWidth;
    private javax.swing.JRadioButton noOrder;
    private javax.swing.JPanel orderDetailsPanel;
    private javax.swing.JRadioButton yesOrder;
    // End of variables declaration//GEN-END:variables
}
