/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Omar
 */
public class Quote extends javax.swing.JFrame {

    /**
     * Creates new form Quote
     */
    public Quote() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        orderDetailsPanel = new javax.swing.JPanel();
        lblOrderQuantity = new javax.swing.JLabel();
        lblQuantity = new javax.swing.JLabel();
        lblOrderSealableTop = new javax.swing.JLabel();
        lblSealableTop = new javax.swing.JLabel();
        lblReinforcement = new javax.swing.JLabel();
        lblOrderReinforcement = new javax.swing.JLabel();
        lblOrderColours = new javax.swing.JLabel();
        lblColour = new javax.swing.JLabel();
        lblDimensions = new javax.swing.JLabel();
        lblLength = new javax.swing.JLabel();
        lblWidth = new javax.swing.JLabel();
        lblHeight = new javax.swing.JLabel();
        lblOrderHeight = new javax.swing.JLabel();
        lblOrderWidth = new javax.swing.JLabel();
        lblOrderLength = new javax.swing.JLabel();
        lblQuantity1 = new javax.swing.JLabel();
        lblOrderGradeOfCard = new javax.swing.JLabel();
        lblOrderTotal = new javax.swing.JLabel();
        lblTotalAmount = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        orderDetailsPanel2 = new javax.swing.JPanel();
        lblOrderQuantity2 = new javax.swing.JLabel();
        lblQuantity4 = new javax.swing.JLabel();
        lblOrderSealableTop2 = new javax.swing.JLabel();
        lblSealableTop2 = new javax.swing.JLabel();
        lblReinforcement2 = new javax.swing.JLabel();
        lblOrderReinforcement2 = new javax.swing.JLabel();
        lblOrderColours2 = new javax.swing.JLabel();
        lblColour2 = new javax.swing.JLabel();
        lblDimensions2 = new javax.swing.JLabel();
        lblLength2 = new javax.swing.JLabel();
        lblWidth2 = new javax.swing.JLabel();
        lblHeight2 = new javax.swing.JLabel();
        lblOrderHeight2 = new javax.swing.JLabel();
        lblOrderWidth2 = new javax.swing.JLabel();
        lblOrderLength2 = new javax.swing.JLabel();
        lblQuantity5 = new javax.swing.JLabel();
        lblOrderGradeOfCard2 = new javax.swing.JLabel();
        lblOrderTotal2 = new javax.swing.JLabel();
        lblTotalAmount2 = new javax.swing.JLabel();
        lblSub = new javax.swing.JLabel();
        lblSubTotal = new javax.swing.JLabel();
        btnPrint = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Your orders:");

        orderDetailsPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblOrderQuantity.setText("[quantity]");

        lblQuantity.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblQuantity.setText("Qantity required:");

        lblOrderSealableTop.setText("[yes/no]");

        lblSealableTop.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblSealableTop.setText("Sealable top:");

        lblReinforcement.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblReinforcement.setText("Reinforcement:");

        lblOrderReinforcement.setText("[reinforcement]");

        lblOrderColours.setText("[No. of colours]");

        lblColour.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblColour.setText("Colours needed:");

        lblDimensions.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblDimensions.setText("Dimensions of box (m):");

        lblLength.setText("Length:");

        lblWidth.setText("Width:");

        lblHeight.setText("Height:");

        lblOrderHeight.setText("[height]");

        lblOrderWidth.setText("[width]");

        lblOrderLength.setText("[length]");

        lblQuantity1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblQuantity1.setText("Grade of card:");

        lblOrderGradeOfCard.setText("[grade of card]");

        lblOrderTotal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblOrderTotal.setText("Order total:");

        lblTotalAmount.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblTotalAmount.setText("£[total]");

        javax.swing.GroupLayout orderDetailsPanelLayout = new javax.swing.GroupLayout(orderDetailsPanel);
        orderDetailsPanel.setLayout(orderDetailsPanelLayout);
        orderDetailsPanelLayout.setHorizontalGroup(
            orderDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(orderDetailsPanelLayout.createSequentialGroup()
                .addGroup(orderDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(orderDetailsPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(orderDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDimensions)
                            .addComponent(lblColour)
                            .addComponent(lblReinforcement)
                            .addComponent(lblSealableTop)
                            .addComponent(lblQuantity1)
                            .addComponent(lblQuantity))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(orderDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblOrderQuantity)
                            .addComponent(lblOrderSealableTop)
                            .addComponent(lblOrderReinforcement)
                            .addGroup(orderDetailsPanelLayout.createSequentialGroup()
                                .addGroup(orderDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblHeight)
                                    .addComponent(lblWidth)
                                    .addComponent(lblLength))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(orderDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblOrderLength)
                                    .addComponent(lblOrderWidth)
                                    .addComponent(lblOrderHeight)))
                            .addComponent(lblOrderColours)
                            .addComponent(lblOrderGradeOfCard)))
                    .addGroup(orderDetailsPanelLayout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(lblOrderTotal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblTotalAmount)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        orderDetailsPanelLayout.setVerticalGroup(
            orderDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, orderDetailsPanelLayout.createSequentialGroup()
                .addGroup(orderDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDimensions)
                    .addGroup(orderDetailsPanelLayout.createSequentialGroup()
                        .addGroup(orderDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblLength)
                            .addComponent(lblOrderLength))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(orderDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblWidth)
                            .addComponent(lblOrderWidth))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(orderDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblHeight)
                            .addComponent(lblOrderHeight))))
                .addGap(15, 15, 15)
                .addGroup(orderDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblColour)
                    .addComponent(lblOrderColours))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(orderDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblReinforcement)
                    .addComponent(lblOrderReinforcement))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(orderDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSealableTop)
                    .addComponent(lblOrderSealableTop))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(orderDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblQuantity1)
                    .addComponent(lblOrderGradeOfCard))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(orderDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblQuantity)
                    .addComponent(lblOrderQuantity))
                .addGap(18, 18, 18)
                .addGroup(orderDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblOrderTotal)
                    .addComponent(lblTotalAmount))
                .addGap(134, 134, 134))
        );

        jLabel3.setText("Order 1:");

        jLabel4.setText("Order 2:");

        orderDetailsPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblOrderQuantity2.setText("[quantity]");

        lblQuantity4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblQuantity4.setText("Qantity required:");

        lblOrderSealableTop2.setText("[yes/no]");

        lblSealableTop2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblSealableTop2.setText("Sealable top:");

        lblReinforcement2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblReinforcement2.setText("Reinforcement:");

        lblOrderReinforcement2.setText("[reinforcement]");

        lblOrderColours2.setText("[No. of colours]");

        lblColour2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblColour2.setText("Colours needed:");

        lblDimensions2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblDimensions2.setText("Dimensions of box (m):");

        lblLength2.setText("Length:");

        lblWidth2.setText("Width:");

        lblHeight2.setText("Height:");

        lblOrderHeight2.setText("[height]");

        lblOrderWidth2.setText("[width]");

        lblOrderLength2.setText("[length]");

        lblQuantity5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblQuantity5.setText("Grade of card:");

        lblOrderGradeOfCard2.setText("[grade of card]");

        lblOrderTotal2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblOrderTotal2.setText("Order total:");

        lblTotalAmount2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblTotalAmount2.setText("£[total]");

        javax.swing.GroupLayout orderDetailsPanel2Layout = new javax.swing.GroupLayout(orderDetailsPanel2);
        orderDetailsPanel2.setLayout(orderDetailsPanel2Layout);
        orderDetailsPanel2Layout.setHorizontalGroup(
            orderDetailsPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(orderDetailsPanel2Layout.createSequentialGroup()
                .addGroup(orderDetailsPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(orderDetailsPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(orderDetailsPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDimensions2)
                            .addComponent(lblColour2)
                            .addComponent(lblReinforcement2)
                            .addComponent(lblSealableTop2)
                            .addComponent(lblQuantity5)
                            .addComponent(lblQuantity4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(orderDetailsPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblOrderQuantity2)
                            .addComponent(lblOrderSealableTop2)
                            .addComponent(lblOrderReinforcement2)
                            .addGroup(orderDetailsPanel2Layout.createSequentialGroup()
                                .addGroup(orderDetailsPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblHeight2)
                                    .addComponent(lblWidth2)
                                    .addComponent(lblLength2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(orderDetailsPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblOrderLength2)
                                    .addComponent(lblOrderWidth2)
                                    .addComponent(lblOrderHeight2)))
                            .addComponent(lblOrderColours2)
                            .addComponent(lblOrderGradeOfCard2)))
                    .addGroup(orderDetailsPanel2Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(lblOrderTotal2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblTotalAmount2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        orderDetailsPanel2Layout.setVerticalGroup(
            orderDetailsPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, orderDetailsPanel2Layout.createSequentialGroup()
                .addGroup(orderDetailsPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDimensions2)
                    .addGroup(orderDetailsPanel2Layout.createSequentialGroup()
                        .addGroup(orderDetailsPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblLength2)
                            .addComponent(lblOrderLength2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(orderDetailsPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblWidth2)
                            .addComponent(lblOrderWidth2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(orderDetailsPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblHeight2)
                            .addComponent(lblOrderHeight2))))
                .addGap(15, 15, 15)
                .addGroup(orderDetailsPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblColour2)
                    .addComponent(lblOrderColours2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(orderDetailsPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblReinforcement2)
                    .addComponent(lblOrderReinforcement2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(orderDetailsPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSealableTop2)
                    .addComponent(lblOrderSealableTop2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(orderDetailsPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblQuantity5)
                    .addComponent(lblOrderGradeOfCard2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(orderDetailsPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblQuantity4)
                    .addComponent(lblOrderQuantity2))
                .addGap(18, 18, 18)
                .addGroup(orderDetailsPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblOrderTotal2)
                    .addComponent(lblTotalAmount2))
                .addGap(134, 134, 134))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(orderDetailsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(orderDetailsPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(90, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(orderDetailsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(orderDetailsPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(74, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel1);

        lblSub.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblSub.setText("Sub-total:");

        lblSubTotal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblSubTotal.setText("£99.98");

        btnPrint.setText("Print");

        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnPrint, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblSub)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblSubTotal)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 421, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSub)
                    .addComponent(lblSubTotal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPrint)
                    .addComponent(jButton1))
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
     
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Quote.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Quote.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Quote.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Quote.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Quote().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPrint;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblColour;
    private javax.swing.JLabel lblColour1;
    private javax.swing.JLabel lblColour2;
    private javax.swing.JLabel lblDimensions;
    private javax.swing.JLabel lblDimensions1;
    private javax.swing.JLabel lblDimensions2;
    private javax.swing.JLabel lblHeight;
    private javax.swing.JLabel lblHeight1;
    private javax.swing.JLabel lblHeight2;
    private javax.swing.JLabel lblLength;
    private javax.swing.JLabel lblLength1;
    private javax.swing.JLabel lblLength2;
    private javax.swing.JLabel lblOrderColours;
    private javax.swing.JLabel lblOrderColours1;
    private javax.swing.JLabel lblOrderColours2;
    private javax.swing.JLabel lblOrderGradeOfCard;
    private javax.swing.JLabel lblOrderGradeOfCard1;
    private javax.swing.JLabel lblOrderGradeOfCard2;
    private javax.swing.JLabel lblOrderHeight;
    private javax.swing.JLabel lblOrderHeight1;
    private javax.swing.JLabel lblOrderHeight2;
    private javax.swing.JLabel lblOrderLength;
    private javax.swing.JLabel lblOrderLength1;
    private javax.swing.JLabel lblOrderLength2;
    private javax.swing.JLabel lblOrderQuantity;
    private javax.swing.JLabel lblOrderQuantity1;
    private javax.swing.JLabel lblOrderQuantity2;
    private javax.swing.JLabel lblOrderReinforcement;
    private javax.swing.JLabel lblOrderReinforcement1;
    private javax.swing.JLabel lblOrderReinforcement2;
    private javax.swing.JLabel lblOrderSealableTop;
    private javax.swing.JLabel lblOrderSealableTop1;
    private javax.swing.JLabel lblOrderSealableTop2;
    private javax.swing.JLabel lblOrderTotal;
    private javax.swing.JLabel lblOrderTotal1;
    private javax.swing.JLabel lblOrderTotal2;
    private javax.swing.JLabel lblOrderWidth;
    private javax.swing.JLabel lblOrderWidth1;
    private javax.swing.JLabel lblOrderWidth2;
    private javax.swing.JLabel lblQuantity;
    private javax.swing.JLabel lblQuantity1;
    private javax.swing.JLabel lblQuantity2;
    private javax.swing.JLabel lblQuantity3;
    private javax.swing.JLabel lblQuantity4;
    private javax.swing.JLabel lblQuantity5;
    private javax.swing.JLabel lblReinforcement;
    private javax.swing.JLabel lblReinforcement1;
    private javax.swing.JLabel lblReinforcement2;
    private javax.swing.JLabel lblSealableTop;
    private javax.swing.JLabel lblSealableTop1;
    private javax.swing.JLabel lblSealableTop2;
    private javax.swing.JLabel lblSub;
    private javax.swing.JLabel lblSubTotal;
    private javax.swing.JLabel lblTotalAmount;
    private javax.swing.JLabel lblTotalAmount1;
    private javax.swing.JLabel lblTotalAmount2;
    private javax.swing.JLabel lblWidth;
    private javax.swing.JLabel lblWidth1;
    private javax.swing.JLabel lblWidth2;
    private javax.swing.JPanel orderDetailsPanel;
    private javax.swing.JPanel orderDetailsPanel1;
    private javax.swing.JPanel orderDetailsPanel2;
    // End of variables declaration//GEN-END:variables
}
